clear all; close all;


ncfile1 = '/Volumes/T7 Touch/Erie/Output.00/erie_00_AED.nc';
ncfile2 = '/Volumes/T7 Touch/Erie/Output.01/erie_01_AED.nc';

%ncfile1 = 'F:/Output.n/erie_AED.nc';
%ncfile2 = 'F:/Output.n/erie_AED.nc';

varname = {...
 'WQ_PHS_FRP',...
%  'WQ_NIT_AMM',...
%  'WQ_NIT_NIT',...
%  'WQ_BIV_FILTFRAC',...
%  'WQ_PHS_FRP_ADS',...
%  'WQ_OGM_DOC',...
%  'WQ_OGM_POC',...
%  'WQ_OGM_DON',...
%  'WQ_OGM_PON',...
};

def.cAxis(1).value = [-0.005 0.005];   %'WQ_DIAG_TOT_TN',...
def.cAxis(2).value = [0 0.25];  %'WQ_DIAG_TOT_TP',...
def.cAxis(3).value = [0 15];   %'WQ_DIAG_TOT_TOC',...
def.cAxis(4).value = [0 600];	%'WQ_DIAG_TOT_TSS',...
def.cAxis(5).value = [0 750];  %'WQ_DIAG_TOT_LIGHT',...
def.cAxis(6).value = [0 400];  %'WQ_DIAG_TOT_PAR',...
def.cAxis(7).value = [0 50];  %'WQ_DIAG_TOT_UV',...
def.cAxis(8).value = [0 2];   %'WQ_DIAG_TOT_EXTC',...
def.cAxis(9).value = [0 50];   %'WQ_DIAG_PHY_TCHLA',...

def.cAxis(1).clip = [-0.0005 0.0005];   %'WQ_DIAG_TOT_TN',...
def.cAxis(2).clip = [0 0.25];  %'WQ_DIAG_TOT_TP',...
def.cAxis(3).clip = [0 15];   %'WQ_DIAG_TOT_TOC',...
def.cAxis(4).clip = [0 600];	%'WQ_DIAG_TOT_TSS',...
def.cAxis(5).clip = [0 750];  %'WQ_DIAG_TOT_LIGHT',...
def.cAxis(6).clip = [0 400];  %'WQ_DIAG_TOT_PAR',...
def.cAxis(7).clip = [0 50];  %'WQ_DIAG_TOT_UV',...
def.cAxis(8).clip = [0 2];   %'WQ_DIAG_TOT_EXTC',...
def.cAxis(9).clip = [0 50];   %'WQ_DIAG_PHY_TCHLA',...

def.conv(1) = 30.91/1000;   %'WQ_DIAG_TOT_TN',...



start_timeave = datenum(2013,06:10,01);
end_timeave = datenum(2013,07:11,01);

%titletxt = 'My variable name (units)';

% del_caxis = [-1 1];
% del_clip = [-0.1 0.1];

% outname = 'theplot.png';

for i = 1:length(start_timeave)
    for j = 1:length(varname)
        
        titletxt = regexprep(varname{j},'_',' ');
        
        outname = [datestr(start_timeave(i),'yyyy_mm_dd'),' ',varname{j},'.png'];
       
        erie_delmap_v2(ncfile1,ncfile2,varname{j},titletxt,def.cAxis(j).value,def.cAxis(j).clip,...
            start_timeave(i),end_timeave(i),outname,def.conv(j));
    end
end

%_______________________________

% erie_delmap_v2(ncfile1,ncfile2,var,titletxt,del_caxis,del_clip,start_timeave,end_timeave,outname);
% 
% del_caxis = [-2 2];
% del_clip = [-0.1 0.1];
% 
% outname = 'theplot2.png';
% 
% erie_delmap_v2(ncfile1,ncfile2,var,titletxt,del_caxis,del_clip,start_timeave,end_timeave,outname);
